newfold-labs/wp-module-patterns

includes/CSSUtilities.php
This hook gives consumers the flexibility to load `nfd-wonder-blocks-utilities` as needed via `do_action('enqueue_nfd_wonder_blocks_utilities')`.
Context:
When pulling blocks from the cloud patterns endpoint into the onboarding live previews, we avoid loading all the block editor assets (this prevents page lag when we have 6 previews in a page), we want to pull only what is necessary to render blocks in the preview. Hence, we prevent using the `enqueue_block_editor_assets` hook and wanted a way to load the CSS utilities.
=> Add a hook to enqueue `nfd-wonder-blocks-utilities`

includes/Library/Categories.php, src/components/Modal/Sidebar/Categories.jsx, src/components/Modal/Sidebar/ListElement.jsx, src/hooks/useCategories.js
This PR ensures that the UI will correctly show item count in each category. This expects https://patterns.hiive.cloud/categories to return `count` for each item in `data` array.
Can be safely merged even if the API still does not return count.
=> Add support for category count

includes/CSSUtilities.php
1. Fixes CSS Utilities warning on 6.3 in both Onboarding and the Site Editor.
2. `enqueue_block_assets` does the job of `wp_enqueue_scripts` and `enqueue_block_editor_assets`.
=> Use `enqueue_block_assets` for CSSUtilities

includes/Library/Admin.php, package-lock.json, package.json, src/components/Modal/Content/Content.jsx, src/components/Modal/Content/ContentTitle.jsx, src/components/Modal/Content/UpdateNotice.jsx, src/constants.js
This PR introduces a new feature in the module that warns users when their WordPress installation does not meet the minimum version requirement for optimal functionality. The notice prompts users to update their WordPress installation to avoid potential issues.
- Adds a new **UpdateNotice** component that leverages Gutenberg's Notice component to display a warning message.
- Utilizes the compare-versions library to robustly compare the current WordPress version with the minimum required version.
- Introduces two new constants, WP_VERSION and MIN_REQUIRED_WP_VERSION, that hold the current WordPress version and the minimum required version, respectively.
=> Add Update Notice for Minimum WP Version Requirement

includes/Library/Admin.php, includes/Library/Items.php
This pull request introduces Wonder Blocks patterns directly into the WordPress Core Patterns modal. Users will now have immediate access to these new patterns, making it easier to insert them into posts and pages.
**Changes**
- Integrated Wonder Blocks patterns into the core Patterns modal via the register_block_patterns function.
- Added new categories, "Wonder Blocks - Category", to the Patterns modal for better organization.
- Unregistered Yith Wonder block patterns to maintain a clean user interface.
**Testing**
- Navigate to any post or page editor.
- Open the Block Inserter and navigate to Patterns tab.
- Browse to the "Wonder Blocks" categories.
- Confirm that the Wonder Blocks patterns are available and functional.
**Screenshots**
=> Display Wonder Blocks patterns in core patterns modal

tests/cypress/integration/wonder-blocks.cy.js
This adds a basic cypress test to verify wonderblock button is present and functional.
Ideally, we can expand on this and include more tests to ensure the wonder block modal contains the expected content and the interface works as expected. These tests are run in every plugin PR so we can make sure modules function as expected with each update.
We can even stub/intercept the API endpoints in the test so we receive consistent responses which will be pulled in and tests can be run against that response.
=> Add basic cypress test

tests/cypress/integration/wonder-blocks.cy.js
This forces a click on `body`, which closes gutenberg's welcome guide (which is open by default) so the test can proceed. If no welcome guide loads, this is just an extra click on the body element.
Currently, in the HostGator plugin, we're excluding this test. Once this is merged we can include this module's tests again.
=> Fix welcome guide interfering with cypress test

tests/cypress/integration/wonder-blocks.cy.js
The test became outdated. This fix ensures the button is the target of clicks and that the welcome guide modal is closed at the proper time.
I have the test copied in the bluehost latest release so we don't need this to be released urgently, as the plugin test overrides this one, but will be good to have a working test in place here for the next release.
=> Fix wonder block button test

includes/Api/RemoteRequest.php
Remove param data from RemoteRequest to prevent cache misses since the data is not used yet by the platform.
=> Remove param data from RemoteRequest

src/components/Modal/Content/UpdateNotice.jsx, src/helpers/index.js, src/helpers/utils.js
Related JIRA : https://jira.newfold.com/browse/PRESS2-1879
The compare-version library used in the <UpdateNotice /> component to compare wordpress versions throws an error when the semver format is not maintained as MAJOR.MINOR.PATCH. In case of 6.5rc-2, it is expecting the format to be 6.5.0rc-2, ie. it is missing the PATCH.  I have added 0 for versions missing the Minor and Patch in semver-version keeping the release suffix like RC or alpha, beta as is. 
Additionally put the code in try catch block to handle any errors and that the error doesn't stop the WonderBlocks modal from opening.
=> added semver format check for versions missing minor and patch

src/styles/_form.scss
On older WP versions:
On version 6.5, the issue was:
After the fix:
This does not exactly match the older versions but works well with the new `SearchControl` component.
=> WordPress 6.5: Update modal search bar CSS

src/helpers/analytics.js
This PR introduces a validation check in the trackHiiveEvent function to ensure that the event's label key is present and not empty before proceeding with sending the event to Hiive.
=> Add validation to ensure label key is present before sending event to Hiive

src/components/Modal/Content/Views/About.jsx
As each of the hosting brand plugins are prefixed with `The` the preceding `the` causes duplicates.
=> Remove the duplicate in About view

postcss.config.js
Uses `ctx.env` to detect `--env production` from npm script that was causing minification in the utilities file not to take.
Cuts 20kb from frontends and editor 😎
=> Fix minification using postcss detection of env

includes/CSSUtilities.php
This PR updates the CSSUtilities class to load CSS and JS assets from a remote URL. If the remote assets are unavailable, the fallback to local assets is triggered.
=> PRESS0-1788 Load CSS and JS utilities from remote

src/components/Modal/Modal.jsx, src/components/ToolbarButton.jsx
WonderBlocks library button was displaying blue text color on hover instead of white.
=> Fix WonderBlocks Library button color on hover

includes/Admin/CTA.php
* Adds WonderBlocks button in lieu of long sentance
* Adds button to Post screen as well
* Adds ability to show and hide button independently on both screens without deactivating WonderBlocks entirely or requiring custom CSS to hide it
* Matches URLs from launchpads
Did my best to first tie-in with the `Apply` button and screen options but hit a few roadblocks. Feel free to adjust if you can get it, but this should be secure and functional.
https://github.com/user-attachments/assets/c9295f2f-5e1c-44e0-bf80-4382f141f66f
=> Use Button(s) on Edit Screen, Show Button on Edit Posts, Allow Users to Disable

src/components/Modal/Content/DesignList/NoResults.jsx
In #127 changing of Icons, I didn't address the NoResults view for favorites which is referencing icon maps that no longer exist.
Currently clicking the Favorites navigation item with Favorites stored works just fine. Clicking Favorites with no favorites triggers the `<NoResults />` component and the missing icons cause the modal to crash.
1. This corrects the icon mappings for the two categories there.
2. This removes the CSS class previously needed for WordPress icons that isn't required for Lucide to inherit the proper colors.
https://github.com/user-attachments/assets/f49bbfd4-5391-48ea-b2c8-cd39b0834ae7
=> Bugfix: Empty Favorites navigation triggers missed icon mapping, breaks modal

src/styles/modal/modal.scss
New component styles introduced for the Toggle Group component in Gutenberg 19.8 and coming in the next major WordPress release in Spring 2025 break the usage in WonderBlocks library modal.
This presents today with customers who have the Gutenberg plugin active.
https://jira.newfold.com/browse/PRESS8-158
=> Enforce modal sidebar toggle group background with new core component styles

tests/cypress/integration/wonder-blocks.cy.js
See [PRESS10-34](https://jira.newfold.com/browse/PRESS10-34)
Small test-related change to add the testIsolation flag to the test and combine into one run.
=> Update cypress test with testIsolation

includes/Services/PluginService.php
This PR prevents Yoast redirect after it's installed through the WonderBlocks modal.
=> Prevent redirect after Yoast Premium installation
